# Generated by Django 4.1.3 on 2022-11-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
